<?php

declare(strict_types=1);

?><p class="card-text">
    <img src="<?= $this->image('psi.png'); ?>" class="float-start me-3" alt="psi">
    This psychological questionnaire will reveal the inner secrets of your personality. These secrets include how you
    perceive the world, how you get along with others, and how you fit into a variety of institutional settings such as
    the workplace. This instrument&mdash;which is of unparalleled thoroughness, validity, and reliability&mdash;will, at
    its conclusion, categorize you in a characterological type with perfect precision. Be warned: you may yet be
    unprepared for such a life-changing insight into the self&hellip;
</p>
<a href="<?= $this->url('question'); ?>" class="btn btn-primary">Begin the Test!</a>
