<?php

declare(strict_types=1);

use CliffordVickrey\MoyersBiggs\Infrastructure\View\ViewModel;

/** @var ViewModel $child */
$child = $this->child;
$partial = $child->getPartial();

$tab = match ($partial) {
    'default', 'question', 'results' => 'test',
    'log' => 'log',
    'stats' => 'stats',
    default => ''
};

?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width,initial-scale=1" name="viewport">
    <title>The Moyers-Biggs Personality Test</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-12 mt-3">
            <div class="col-12 col-xl-6 offset-xl-3">
                <div class="card">
                    <h5 class="card-header">The Moyers-Biggs Personality Test</h5>
                    <div class="card-body">
                        <!-- content -->
                        <?= $this->content; ?>
                        <!-- /content -->
                    </div>
                    <div class="card-footer">
                        <ul class="nav nav-pills card-header-pills">
                            <li class="nav-item">
                                <a class="nav-link<?= 'test' === $tab ? ' active' : ''; ?>"
                                   href="<?= $this->url(''); ?>">
                                    Test
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link<?= 'log' === $tab ? ' active' : ''; ?>"
                                   href="<?= $this->url('log'); ?>">
                                    Log
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link<?= 'stats' === $tab ? ' active' : ''; ?>"
                                   href="<?= $this->url('stats'); ?>">
                                    Stats
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="row small">
        <div class="col-12">
            <nav class="navbar navbar-expand text-center">
                <ul class="navbar-nav ms-auto me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="https://www.cliffordvickrey.com">cliffordvickrey.com</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Source</a>
                    </li>
                </ul>
            </nav>
        </div>
    </footer>
</div>
<?php if ($child->getParams()['js'] ?? false) { ?>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <script src="<?= $this->script('app.js'); ?>"></script>
<?php } ?>
</body>
</html>